    <div id="social">
      <a href="http://www.facebook.com/chapelvancouver" target="_blank" class="icon-facebook" alt="Facebook" title="Follow us on Facebook"></a>
      <a href="http://twitter.com/ChapelVancouver" target="_blank" class="icon-twitter" alt="Twitter" title="Follow us on Twitter"></a>
      <a href="http://instagram.com/ChapelVancouver" target="_blank" class="icon-instagram" alt="Instagram" title="Follow us on Instagram"></a>
    </div><!-- end of social -->
